{{- if .Values.elasticsearch.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ontology-hub.fullname" . }}-elasticsearch
  labels:
    {{- include "ontology-hub.labels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
data:
  elasticsearch.yml: |
    discovery.type: single-node
    network.host: 0.0.0.0
    xpack.security.enabled: false
    cluster.routing.allocation.disk.threshold_enabled: false
{{- end }}
